services:
  decktape:
    command: ["--size", "${PDF_VIEWPORT:-{{ cookiecutter.pdf_viewport }}}", "reveal", "http://slides?showNotes=true", "{{ cookiecutter.repo_name }}.pdf"]
    depends_on:
      - nginx
    image: astefanutti/decktape:2.8.3@sha256:1a941d17c54e79ce812019a7f89553c5ddbd4109425fe87e18a4506530c7cc3c
    volumes:
      - .:/slides
  nginx:
    image: nginx:1.15.6-alpine@sha256:94e890939a012d8494ac62a0cf6177c57f97522b35e231dad676e089e309d49d
    networks:
      default:
        aliases:
          - slides
    volumes:
      - .:/usr/share/nginx/html:ro
version: '3'
