services:
  decktape:
    command: ["--size", "${PDF_VIEWPORT:-{{ cookiecutter.pdf_viewport }}}", "reveal", "http://slides?showNotes=true", "{{ cookiecutter.repo_name }}.pdf"]
    depends_on:
      - nginx
    image: astefanutti/decktape:2.8.3@sha256:1a941d17c54e79ce812019a7f89553c5ddbd4109425fe87e18a4506530c7cc3c
    volumes:
      - .:/slides
  nginx:
    image: nginx:1.14.0-alpine@sha256:3d36a2c9513a5aa6aa6c41b076201d468bdb94c4f2b4c6e55d32a461ac8f00ee
    networks:
      default:
        aliases:
          - slides
    volumes:
      - .:/usr/share/nginx/html:ro
version: '3'
