services:
  decktape:
    command: ["--size", "${PDF_VIEWPORT:-{{ cookiecutter.pdf_viewport }}}", "reveal", "http://slides?showNotes=true", "{{ cookiecutter.repo_name }}.pdf"]
    depends_on:
      - nginx
    image: astefanutti/decktape:2.11.0@sha256:1b86faa1ac4af1457237845a7a7bfc952f06e0cf5466a1fd369b2bc0a1afd231
    volumes:
      - .:/slides
  nginx:
    image: nginx:1.14.0-alpine@sha256:b4f69b336db828ccdd0cdb6d3257f60cc8c5534cef6d08c2131d9a4950e893cf
    networks:
      default:
        aliases:
          - slides
    volumes:
      - .:/usr/share/nginx/html:ro
version: '3'
