services:
  decktape:
    command: ["--size", "${PDF_VIEWPORT:-{{ cookiecutter.pdf_viewport }}}", "reveal", "http://slides?showNotes=true", "{{ cookiecutter.repo_name }}.pdf"]
    depends_on:
      - nginx
    image: astefanutti/decktape:2.8.3@sha256:1a941d17c54e79ce812019a7f89553c5ddbd4109425fe87e18a4506530c7cc3c
    volumes:
      - .:/slides
  nginx:
    image: nginx:1.31.5-alpine@sha256:bd43d3d8fdbbe597c36fea489886796466a9ea5b662e8c50897d53e190c88a3d
    networks:
      default:
        aliases:
          - slides
    volumes:
      - .:/usr/share/nginx/html:ro
version: '3'
